spring:
  application:
    name: mock-banking-api

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
      format_sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
  test:
    database:
      replace: none

  datasource:
    url: jdbc:mysql://mysql:3306/banking?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root1234!!

server:
  port: ${SERVER_PORT:8081} # 포트를 환경 변수로 설정

client:
  bank:
    ryan: ${RYAN_BANK:http://localhost:8081/ryan-bank} # 라이언뱅크의 경로
    chunsik: ${CHUNSIK_BANK:http://localhost:8082/chunsik-bank} # 춘식뱅크의 경로
