spring:
  profiles:
    active: default
  application:
    name: banking-api

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://mysql:3306/banking?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root1234!!

  data:
    redis:
      host: ${SPRING_REDIS_HOST:redis}
      port: ${SPRING_REDIS_PORT:6379}
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
        shutdown-timeout: 100

client:
  bank:
    ryan: ${RYAN_BANK:http://localhost:8081/ryan-bank} # 라이언뱅크의 경로
    chunsik: ${CHUNSIK_BANK:http://localhost:8082/chunsik-bank} # 춘식뱅크의 경로

feign:
  client:
    config:
      default:
        connectTimeout: 10000 # 연결 타임아웃 (밀리초)
        readTimeout: 10000    # 읽기 타임아웃 (밀리초)

resilience4j.circuitbreaker:
  instances:
    ryan-banking-api:
      register-health-indicator: true
      sliding-window-type: COUNT_BASED
      sliding-window-size: 10
      failure-rate-threshold: 50
      wait-duration-in-open-state: 30s

    chunsik-banking-api:
      register-health-indicator: true
      sliding-window-type: COUNT_BASED
      sliding-window-size: 10
      failure-rate-threshold: 50
      wait-duration-in-open-state: 30s

management:
  endpoints:
    web:
      exposure:
        include: health
  health:
    redis:
      enabled: true

logging:
  level:
    feign: DEBUG
    io.github.resilience4j: DEBUG
